require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

permissions_path = '../node_modules/react-native-permissions/ios'

pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

target 'LibraryApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'LibraryAppTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'LibraryApp-tvOS' do
  # Pods for LibraryApp-tvOS

  target 'LibraryApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
